package com.stock.market.stockprice.entity;

import java.util.Date;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.stock.market.stockprice.config.DataTypeConvertedClass;

import lombok.Getter;
import lombok.Setter;
/**
 * @author Roshini Entity for stockPrices
 *
 */
@Getter
@Setter
@DynamoDBTable(tableName = "stockPrice")
public class Price {

	@DynamoDBAutoGeneratedKey
	@Id
//	@DynamoDBIndexHashKey(globalSecondaryIndexName = "id-index")
	@DynamoDBHashKey(attributeName ="id")
	private String id;

	
	@DynamoDBAttribute(attributeName ="cmpyCode")
//	@DynamoDBIndexHashKey(globalSecondaryIndexName = "cmpyCode-index")
	private String companyCode;
	
	@DynamoDBAttribute(attributeName ="stckPrice")
	private double StckPrice;
	
	@DynamoDBAttribute(attributeName ="creationDate")
//	@DynamoDBHashKey
//	@DynamoDBTypeConverted(converter = DataTypeConvertedClass.class)
//	@DynamoDBIndexHashKey(globalSecondaryIndexName = "creationDate-index")
	private Date creationDate;

	@Override
	public String toString() {
		return "Price [id=" + id + ", companyCode=" + companyCode + ", StckPrice=" + StckPrice + ", creationDate="
				+ creationDate + "]";
	}

}
