package com.stock.market.company.entity;

import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @author Roshini Entity for companyDetails
 *
 */
@Getter
@Setter
@ToString
@DynamoDBTable(tableName = "companyDetails")
public class CompanyDetails {

	
	@DynamoDBAutoGeneratedKey
	@DynamoDBAttribute(attributeName ="id")
	private String id;

	@DynamoDBHashKey(attributeName ="cmpyCode")
	@DynamoDBAttribute(attributeName ="cmpyCode")
	private String companyCode;

	@DynamoDBAttribute(attributeName ="cmpyName")
	private String companyName;

	@DynamoDBAttribute(attributeName ="cmpyCeo")
	private String companyCEO;

	@DynamoDBAttribute(attributeName ="cmpyTurnOver")
	@Size(min = 9)
	private String companyTurnOver;
	
	@DynamoDBAttribute(attributeName ="cmpyWebsite")
	private String companyWebsite;

	@DynamoDBAttribute(attributeName ="stckExchange")
	private String stockExchange;


}
